### ISSUE TITLE
m+ completed

### ISSUE THREAD

**Issue by G1ak1** [Sefriol/MethodAltManager#3]
Hey there..thanks so much for updating this you are a life saver :)

One small thing i noticed. It doesn't show the highest m+ completed per alt for the week. Is that bcs you changed it to be bfa ready or some bug? 

thanks in advance 

best regards

**Comment by Sefriol** [comment]
Hey, thanks for a report! Can you tell how your keys are spelled out in the Alt Manager? 

I made a modification into how the current m+ content is defined, so it might have changed some things.

Edit: Also, could you tell what instances you have run. I'm not able to replicate this problem.

**Comment by G1ak1** [comment]
![alts](https://user-images.githubusercontent.com/29663409/43318179-77a9cac2-91a8-11e8-88b9-e9ea188e6ee2.png)

Check monk. I have done a +2 Maw of Souls. It shows 0 though. Also last week i did a +16 eye on priest and it wasn't showing either.

**Comment by Sefriol** [comment]
Are you sure that you have the latest version installed? (from 2 days ago)

Previously I had API done differently, and later on changed it to more reliable API and the problem, that you mentioned, disappeared from me atleast.

Currently I'm not able to replicate this problem.

If you are absolutely sure that you have the latest version could you do the following steps:

1. Do a **fresh** login to a Character that has completed atleast one m+ dungeon
2. Open your Alt Manager
3. Check the number for Highest m+ done for the character that you have logged in. Is this correct?
4. If the number is correct, login to another character that has completed a mythic+ and do the steps 1-3 again. If the number is incorrect, close the manager.
5. Open the Mythic Plus page (usually bound to `i`) which should show you the picture of chest of highest M+ done
6. Open the Alt Manager again. 
7. Did the number change?

If you are stuck in between steps 1-3 all the time, let me know.

Also are you playing on US or EU? I have tested the weekly reset property on EU, so that might be incorrect for US.

**Comment by G1ak1** [comment]
Hey again. Yeah it was an older version. All good now thanks for your help :)
